#!/usr/bin/env bash
# Singularity Scanner — first-time LXC bootstrap.
#
# Provisions a single Debian 12 LXC with Postgres + Node 24 + the app + systemd.
# Run AS ROOT on a fresh LXC:
#
#   curl -fsSL https://raw.githubusercontent.com/nakiruu/singscanner/main/scripts/init-lxc.sh -o init-lxc.sh
#   chmod +x init-lxc.sh && ./init-lxc.sh
#
# Or, if you've already cloned the repo:
#   ./scripts/init-lxc.sh
#
# Re-runnable. Existing users, dbs, and units are detected and reused.
#
# Overridable via env vars:
#   REPO_URL    (default https://github.com/nakiruu/singscanner.git)
#   BRANCH      (default main)
#   INSTALL_DIR (default /opt/singscanner)
#   SERVICE_USER (default singscanner)
#   DB_NAME     (default singscanner)
#   DB_USER     (default singscanner)
#   DB_PASS     (default: generated, printed at the end)

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/nakiruu/singscanner.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/singscanner}"
SERVICE_USER="${SERVICE_USER:-singscanner}"
SERVICE_NAME="singscanner"
DB_NAME="${DB_NAME:-singscanner}"
DB_USER="${DB_USER:-singscanner}"
DB_PASS="${DB_PASS:-}"
NODE_MAJOR=24

log()  { printf '\033[36m[init %s]\033[0m %s\n' "$(date -u +%H:%M:%SZ)" "$*"; }
warn() { printf '\033[33m[init %s WARN]\033[0m %s\n' "$(date -u +%H:%M:%SZ)" "$*" >&2; }
die()  { printf '\033[31m[init %s FAIL]\033[0m %s\n' "$(date -u +%H:%M:%SZ)" "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root"
. /etc/os-release
[ "${ID:-}" = "debian" ] || warn "tested on Debian — detected '$ID', proceeding anyway"

# ---------- 1. apt prerequisites ----------
log "apt update + base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl gnupg git build-essential sudo \
  postgresql postgresql-contrib openssl >/dev/null

# ---------- 2. Node 24 via NodeSource ----------
if ! command -v node >/dev/null || [ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -lt "$NODE_MAJOR" ]; then
  log "installing Node $NODE_MAJOR via NodeSource"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null
  apt-get install -y -qq nodejs >/dev/null
else
  log "node $(node -v) already present"
fi

# ---------- 3. service user ----------
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  log "creating system user $SERVICE_USER"
  adduser --system --group --home "$INSTALL_DIR" --shell /bin/bash "$SERVICE_USER"
else
  log "user $SERVICE_USER already exists"
fi

# ---------- 4. postgres role + database ----------
log "ensuring postgres is running"
systemctl enable --now postgresql >/dev/null

if [ -z "$DB_PASS" ]; then
  DB_PASS="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  GENERATED_PASS=1
fi

# create role idempotently
if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
  log "postgres role $DB_USER already exists; updating password"
  sudo -u postgres psql -c "ALTER USER \"$DB_USER\" WITH PASSWORD '$DB_PASS';" >/dev/null
else
  log "creating postgres role $DB_USER"
  sudo -u postgres psql -c "CREATE USER \"$DB_USER\" WITH PASSWORD '$DB_PASS';" >/dev/null
fi

if sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  log "database $DB_NAME already exists"
else
  log "creating database $DB_NAME owned by $DB_USER"
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

# ---------- 5. clone or refresh repo ----------
if [ ! -d "$INSTALL_DIR/.git" ]; then
  log "cloning $REPO_URL -> $INSTALL_DIR (branch $BRANCH)"
  # If $INSTALL_DIR exists but isn't a repo (e.g. just the user's home), clone into a temp and move.
  if [ -d "$INSTALL_DIR" ] && [ -n "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
    die "$INSTALL_DIR exists and isn't a git checkout. Remove it or set INSTALL_DIR=."
  fi
  git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
else
  log "$INSTALL_DIR is already a git repo; pulling latest $BRANCH"
  git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
  git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
fi
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# ---------- 6. .env ----------
ENV_FILE="$INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  log "writing $ENV_FILE with localhost DATABASE_URL and a fresh NEXTAUTH_SECRET"
  NEXTAUTH_SECRET="$(openssl rand -base64 32)"
  cat >"$ENV_FILE" <<EOF
# Generated by init-lxc.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

DATABASE_URL="postgresql://$DB_USER:$DB_PASS@127.0.0.1:5432/$DB_NAME?schema=public"

NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
NEXTAUTH_URL="http://127.0.0.1:3000"   # change to https://your.domain once NPM is live

GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

ALPACA_API_KEY=""
ALPACA_API_SECRET=""
ALPACA_FEED="iex"

SCANNER_HORIZON="3d"
SCANNER_UNIVERSE="auto"
SCANNER_MAX_SYMBOLS="300"
SCANNER_INTERVAL_S="15"
SCANNER_MOCK="true"
SCANNER_USE_XGBOOST="true"
SCANNER_USE_KRONOS="false"
KRONOS_PATH=""
EOF
  chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
else
  warn "$ENV_FILE already exists; leaving untouched"
  warn "if DB_PASS was regenerated above, you'll need to update DATABASE_URL by hand"
fi

# ---------- 7. install deps + build ----------
log "npm ci (this takes a minute on first run)"
sudo -u "$SERVICE_USER" -- bash -lc "cd $INSTALL_DIR && npm ci"

log "prisma generate"
sudo -u "$SERVICE_USER" -- bash -lc "cd $INSTALL_DIR && npx prisma generate --no-hints"

log "prisma migrate deploy"
sudo -u "$SERVICE_USER" -- bash -lc "cd $INSTALL_DIR && npx prisma migrate deploy"

log "next build"
sudo -u "$SERVICE_USER" -- bash -lc "cd $INSTALL_DIR && npm run build"

# ---------- 8. systemd unit ----------
UNIT_SRC="$INSTALL_DIR/scripts/singscanner.service"
UNIT_DST="/etc/systemd/system/$SERVICE_NAME.service"
if [ -f "$UNIT_SRC" ]; then
  log "installing systemd unit"
  install -m 0644 "$UNIT_SRC" "$UNIT_DST"
else
  warn "systemd unit not found at $UNIT_SRC; writing a minimal fallback"
  cat >"$UNIT_DST" <<EOF
[Unit]
Description=Singularity Scanner
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
Environment=NODE_ENV=production
Environment=PORT=3000
ExecStart=/usr/bin/npm run start
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
fi

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

# ---------- 9. sudoers for deploy.sh ----------
SUDOERS="/etc/sudoers.d/$SERVICE_NAME-deploy"
if [ ! -f "$SUDOERS" ]; then
  log "granting $SERVICE_USER passwordless restart for deploy.sh"
  echo "$SERVICE_USER ALL=(root) NOPASSWD: /bin/systemctl restart $SERVICE_NAME" >"$SUDOERS"
  chmod 440 "$SUDOERS"
fi

# ---------- 10. smoke test ----------
log "waiting for /api/status"
for i in $(seq 1 30); do
  if curl --fail --silent --max-time 2 http://127.0.0.1:3000/api/status >/dev/null; then
    log "service is up — visit http://<lxc-ip>:3000 (or your NPM-fronted domain)"
    break
  fi
  sleep 1
  [ "$i" -eq 30 ] && die "service did not respond on :3000 in 30s — check: journalctl -u $SERVICE_NAME -n 80"
done

# ---------- summary ----------
LXC_IP="$(hostname -I | awk '{print $1}')"
cat <<EOF

────────────────────────────────────────────────────────────────────
  Singularity Scanner is live.

  App URL (LAN):   http://${LXC_IP}:3000
  Service:         systemctl status $SERVICE_NAME
  Logs:            journalctl -u $SERVICE_NAME -f
  Deploy updates:  cd $INSTALL_DIR && sudo -u $SERVICE_USER ./scripts/deploy.sh
EOF

if [ "${GENERATED_PASS:-0}" = "1" ]; then
  cat <<EOF

  Postgres credentials (also in $ENV_FILE):
    db:   $DB_NAME
    user: $DB_USER
    pass: $DB_PASS

  ⚠  Save the password somewhere — it isn't shown again.
EOF
fi

cat <<EOF

  Next steps:
    1. In NPM, add a proxy host pointing your domain at ${LXC_IP}:3000
       (enable Websockets Support so SSE works)
    2. Edit NEXTAUTH_URL in $ENV_FILE to your https domain
    3. Set SCANNER_MOCK="false" + ALPACA_API_KEY/SECRET to use real data
    4. Restart:  sudo systemctl restart $SERVICE_NAME
────────────────────────────────────────────────────────────────────
EOF
